### ISSUE TITLE
[BE] Think about API Endpoints design

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-profiles-backend#1]

**Comment by CloudSalander** [comment]
Attached documentation related to your first design issues.


[Requisitos_producto_ITA_PROFILES.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/12792317/Requisitos_producto_ITA_PROFILES.pdf)

**Comment by j-obiols** [comment]
[IT_PROFILES_ENDPOINTS.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/12856093/IT_PROFILES_ENDPOINTS.pdf)

**Comment by j-obiols** [comment]
[IT_PROFILES_ENDPOINTS.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/12856110/IT_PROFILES_ENDPOINTS.pdf)

**Comment by j-obiols** [comment]
VERSIÓN V.2 (15-10-2023)

Nueva versión con los cambios comentados en la última reunión:  endpoints para gestionar todos los proyectos, sean IT o Freelance, más dos endpoints para relacionar o "desrelacionar" un proyecto con un estudiante, es decir para crear o eliminar registros en la tabla "student_has_projects".

De momento no hay ningún endpoint de gestión de códigos de invitación ni de gestión de roles.

[IT_PROFILES_ENDPOINTS.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/12909482/IT_PROFILES_ENDPOINTS.pdf)
