### ISSUE TITLE
[BE] Apply category filters when listing users

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-backend#100]
Como usuarios Open
Queremos poder filtrar listas de usuarios por Category (Frontend, Backend, Fullstack....)
Para ello vamos a pasar por parámetro del controlador que lista usuarios los filtros de categoria y a crear un caso en el que dichos filtros por categoría se aplican a la consulta del modelo
Sabremos que ésto se cumple cuando podamos aplicar los filtros al ejemplo de la documentación y obtengamos los resultados filtrados.

--- 

![Image](https://github.com/IT-Academy-BCN/ita-profiles-backend/assets/11392091/8d972006-06e2-4ce2-b8f4-b5ab528cb462)

**Rutas**

- http://127.0.0.1:8000/api/v1/student/list/for-home?specialization=Frontend
- http://127.0.0.1:8000/api/v1/student/list/for-home?specialization=Backend
- http://127.0.0.1:8000/api/v1/student/list/for-home?specialization=Fullstack
- http://127.0.0.1:8000/api/v1/student/list/for-home?specialization=Data Science

**Comment by FranEnLaNube** [comment]
This issue has been solved by #104, tested in production, all is good and working 💪
