### ISSUE TITLE
[BE]  How are we going to format the code?

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-profiles-backend#11]

**Comment by CloudSalander** [comment]
Maybe Laravel Pint?
https://laravel.com/docs/10.x/pint

**Comment by j-obiols** [comment]
After studying your proposal, here is what we've found :-):

**LARAVEL PINT** is a **style code fixer**. When Pint is invoked, **it fixes code style issues** following a preset style guide’s **set of rules.** 

The developer/s can decide:

-	**which style guide** will be applied: **laravel** (by default), **PER**, **PSR-12** or **Symfony**,  
-	**when** to run Pint, as it has to be invoked,
-	**where** to run it (on the whole project or on specific files or directories)
-	**how** to run it (**simply inspecting** or also **modifying** the files),
-	to **enable** or **disable** specific rules.

---

Briefly, "a **programming style guide** is an opinionated guide of programming conventions, style, and best practices for a team or project”. Other names are used, generally referring to the same thing: coding guidelines, **coding standards**, or coding conventions.

**PHP – FIG (PHP Framework Interop Group)** is a group created in 2009 to create style guides or coding standards for PHP programmers. The initial goal was to create guides for the most basic aspects and included the participation of the most popular PHP framework’s authors. But later, a more formal structure was created and guides for more complex topics were published. This led to the abandonment of some significant participants (Doctrine and Laravel in 2016, Symfony in 2018, Drupal in 2022, etc.) 

The last guide created by PHP-FIG is the **PER** Coding Style guide, which in june 2022 replaced the **PSR-12** guide, which in turn had previously replaced the **PSR-2** guide.  The PER Coding Style aims to be a continously updated document. 

PSR stands for **PHP Standard Recommendation** and PER stands for **PHP Evolving Recommendation**.

---

In the following links you will find information about **the 4 style guides** that the developers can preset in Laravel Pint:

>  **[LARAVEL](https://github.com/laravel/pint/blob/main/resources/presets/laravel.php)**

 The only information found up to now is the Pint preset file. According to the documentation, Laravel follows the **[PSR-2](https://www.php-fig.org/psr/psr-2/)** coding standard and the **[PSR-4](https://www.php-fig.org/psr/psr-4/)** autoloading standard.

>  **[PER](https://www.php-fig.org/per/coding-style/)** 

>   **[PSR - 12](https://www.php-fig.org/psr/psr-12/)**

>  **[SYMFONY](https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)**

The Simfony coding standards are based on the **[PSR-1](https://www.php-fig.org/psr/psr-1/)**, **PSR-2**, **PSR-4** and **PSR-12** standards.

**Comment by androsrivas** [comment]
amazing research job, @j-obiols !! thank you so much for exposing it so clearly

**Comment by CloudSalander** [comment]
Lets go with PER, guys.
