### ISSUE TITLE
[BE] Think about how to version our API

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-profiles-backend#14]

**Comment by elpupas** [comment]
Here I attach my research on how to version a REST API in Laravel.

[Versioning API.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/13055478/Versioning.API.pdf)

**Comment by elpupas** [comment]
**Here I leave you my research on how to version an API**
![Versioning API.pdf](https://github.com/IT-Academy-BCN/ita-profiles-backend/files/13063196/Versioning.API.pdf)

**Comment by j-obiols** [comment]
Thank you, Peterson, good report!
