### ISSUE TITLE
[BE] Get list of users available to FE

### ISSUE THREAD

**Issue by FranEnLaNube** [IT-Academy-BCN/ita-profiles-backend#46]
Considering that at Figma design, we can see that profiles need to show the following fields:
- Full Name.
- Description (Itinerary?).
- Photo.
- Tags.

And there is also a column with filters.
We found a couple of questions to answer.
Considering that FE developers already have done an approaching tho this through using this JSON:
<details>
<summary>ListOfUsers.JSON</summary>
```
[
  {
    "nombreCompleto": "Juan Pérez",
    "profesion": "Desarrollador Frontend",
    "foto": "./src/assets/img/stud_2.png",
    "lenguajes": ["JavaScript", "React", "HTML", "CSS"],
    "id": 1
  },
  {
    "nombreCompleto": "María García",
    "profesion": "Diseñadora UX/UI",
    "foto": "./src/assets/img/stud_1.png",
    "lenguajes": ["CSS", "Sketch", "InVision"],
    "id": 2
  },
  {
    "nombreCompleto": "Carlos Rodríguez",
    "profesion": "Ingeniero de Software",
    "foto": "./src/assets/img/stud_3.png",
    "lenguajes": ["Java", "PHP", "JavaScript", "React"],
    "id": 3
  },
  {
    "nombreCompleto": "Laura Martínez",
    "profesion": "Desarrolladora Full Stack",
    "foto": "./src/assets/img/stud_1.png",
    "lenguajes": ["JavaScript", "Node.js", "Express", "SQL"],
    "id": 4
  },
  {
    "nombreCompleto": "Elena López",
    "profesion": "Frontend React",
    "foto": "./src/assets/img/stud_2.png",
    "lenguajes": ["CSS", "React", "Figma"],
    "id": 5
  },
  {
    "nombreCompleto": "Alejandro Ruiz",
    "profesion": "Desarrollador Frontend",
    "foto": "./src/assets/img/stud_3.png",
    "lenguajes": ["JavaScript", "Vue.js", "HTML", "CSS"],
    "id": 6
  },
  {
    "nombreCompleto": "Sofía Hernández",
    "profesion": "Diseñadora Gráfica",
    "foto": "./src/assets/img/stud_1.png",
    "lenguajes": ["Illustrator", "Photoshop", "InDesign"],
    "id": 7
  },
  {
    "nombreCompleto": "Martín González",
    "profesion": "Ingeniero de Software",
    "foto": "./src/assets/img/stud_2.png",
    "lenguajes": ["Java", "PHP", "JavaScript", "React"],
    "id": 8
  },
  {
    "nombreCompleto": "Ana Castro",
    "profesion": "Desarrolladora Full Stack",
    "foto": "./src/assets/img/stud_3.png",
    "lenguajes": ["JavaScript", "Node.js", "Express", "SQL"],
    "id": 9
  },
  {
    "nombreCompleto": "Javier Díaz",
    "profesion": "Analista de Datos",
    "foto": "./src/assets/img/stud_1.png",
    "lenguajes": ["Python", "Pandas", "SQL"],
    "id": 10
  }
]
```

</details>

We can see that the "profesion" field it's close to the `itenarary` field in our database, but, also, we can find "Ingeniero de Software" or "Diseñadora gráfica" as examples to demonstrate that those are not following exactly our API options. (`$table->enum('bootcamp', ['front end Developer', 'PHP developer', 'java developer', 'Node.js developer',
                'data scientists']);`

### Filtered students

We are thinking what can be the best option, if send the information already filtered from our API through a specific endpoint or if our frontend workmates prefer to filter them once the whole JSON is gotten with the `/students/index` endpoint.

### States 

We also found at Figma that there are a couple of tags that we haven't approached yet, those are "Contacted", "With an interview" and "All". We need to decide what are we gonna do with this. Is a matter of recruiters?

---

We think that this should be covered by more than one issue, but this is a point to start to talk about this.

@coxen34

**Comment by jordimorillo** [comment]
As this issue can be an "epic" I'll move it to done and extract the little issues from here. Congratulations to the team for this analysis! :)
