### ISSUE TITLE
[BE] Provide a route for frontend to consume students list

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-backend#47]
Dado que en el diseño de figma hay un listado de  estudiantes
Queremos poner a disposición de frontend una ruta en la que puedan consumir un json y usarlo en el listado
Para ello vamos a servir este json desde un controlador con la estructura siguiente
Sabremos que esto se cumple cuando desde https://itaperfils.eurecatacademy.org/<la ruta> podamos obtener el listado de usuarios

**Comment by coxen34** [comment]
Added fake route
