### ISSUE TITLE
[BEFE][SPIKE] Ask Luis about tags

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-backend#48]
Dado que en la lista de estudiantes tenemos unos tags
Queremos entender qué contenido puede haber en este campo y si seria correcto llamarlo skills
Para ello vamos a preguntar a Luis cual es su opinión sobre éste tema
Sabremos que esto se cumple cuando en ésta tarjeta podamos añadir un comentario de aprendizaje sobre nuestra pregunta

SPIKE RESULTS:
-----------------

**Comment by pupadevs** [comment]
**Buenas, ya he hablado con Luisvi referente al tema "tags".**

esta ha sido la conclusión relacionada con el tema tags 🏷️ 
- 📛  **Nombre Tags o Skills:** Lo elegido será llamarlo 'skills' en lugar de 'tags', ya que 'tags' es demasiado genérico. En cambio, el campo con el nombre de 'skills' abordará tanto las habilidades técnicas ('tech skills') como las habilidades blandas ('soft skills').
- 📦 **Creación de Skills:** Las Skills solo la podrán crear los admins, los candidatos solo consumiremos las skills ya creadas por los administradores.
- ℹ️  **Info Adicional:** Las Skills su idea es que se puedan vincular a los proyectos que los candidatos tengan agregado. Referencia: Sección de proyectos LinkedIn.
