### ISSUE TITLE
[BE]Add a fake endpoint that can list 'Datos del bootcamp' for frontend student detail view

### ISSUE THREAD

**Issue by coxen34** [IT-Academy-BCN/ita-profiles-backend#82]
Como usuarios abiertos que entramos a la web
Queremos pasar los datos para el bloque 'Datos del bootcamp'.
Para ello vamos a picar un endpoint fake que devuelva los datos que aparecen en Figma.
Sabremos que esto se cumple cuando desde la vista de swagger en producción podamos obtener la lista que hemos preparado.

**Comment by AlejandroNPereyra** [comment]
Being this endpoint also related to a specific student, we need to update the id field to uuid as the model now requires.
